### ISSUE TITLE
Crash on init if discord_users.json is empty

### ISSUE THREAD

**Issue by mikaelssen** [trgwii/TediCross#1]
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at new DiscordUserMap (/var/TediCross/DiscordUserMap.js:43:15)
    at Object.<anonymous> (/var/TediCross/main.js:46:17)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)

**Comment by mikaelssen** [comment]
Deleting the file will make it boot though~

**Comment by Suppen** [comment]
Fixed in commit 6a6eb20
